### ISSUE TITLE
Wigglemouse

### ISSUE THREAD

**Issue by xalanfx** [samuelskanberg/wigglemouse#1]
Will wigglemouse stop a program from timing out due to inactivity EVEN IF IT'S NOT THE ACTIVE WINDOW?

Thanks

**Comment by samuelskanberg** [comment]
Wigglemouse will "wiggle" the mouse (i.e. move the mouse pointer one pixel up, wait some milliseconds and then move one pixel down). This will happen no matter which windows is active.

The mouse pointer won't be moved if the user is moving the mouse pointer. The delay (e.g. 5 minutes) is counted from the last time the mouse was moved by the user.

So the answer to your question is yes :) Does this answer your question?

**Comment by xalanfx** [comment]
Thanks - I think it doesn't directly.
I use an application for work, and for ease of use, I open 2 copies so that
I can switch between them.
One window is largely NOT used, and times out requiring a fresh login after
about 10 minutes.
I'm guessing that wigglemouse will keep the active window from timing out,
but not the less active one.... but I'll try it and see

Thanks for taking the time to reply

Alan

**Comment by samuelskanberg** [comment]
I don't think I understand what you mean by "timeout". What kind of windows
are we talking about? Are they remote logins (like vnc sessions)?

I created wigglemouse as a very ugly hack to prevent the computer to turn
on the screen saver (or go into hibernation). The reason for this was that
my system would put on the screen saver when I was watching stuff on
youtube.

**Comment by xalanfx** [comment]
It's a secrurity thing that I can't override... if the application is inactive for too long, the application locks and I have to log in again. Think of it as opening 2 copies of MS Word, for example, where if it feels neglected for too long, it locks and you have to re-input a password to continue.... obviously Word doesn't need a password, but you get the idea.

**Comment by samuelskanberg** [comment]
Then no, this application won't help you. It will only wiggle the mouse
pointer where the mouse pointer is at the present time. And since you can't
have two mouse pointers active at the same time it will be hard to keep
your application windows open :(

**Comment by xalanfx** [comment]
Ok,thanks for your time

Alan

**Comment by xalanfx** [comment]
Many thanks for your time
